language: go

go:
  - tip

script:
  - go build ./...
  - go test -v -short -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

before_install: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls